--- #YAML:1.0
name:                     Test-CPAN-Meta-JSON
version:                  0.15
abstract:                 Validate your CPAN META.json files
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  IO::File:               0
  JSON:                   2.15
  Test::More:             0.62
  Test::Builder:          0
recommends:
  Test::CPAN::Meta:       0.13
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  Test::More:             0.70
  Test::Builder::Tester:  0

provides:
  Test::CPAN::Meta::JSON:
    file:     lib/Test/CPAN/Meta/JSON.pm
    version:  0.15
  Test::CPAN::Meta::JSON::Version:
    file:     lib/Test/CPAN/Meta/JSON/Version.pm
    version:  0.15
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-CPAN-Meta-JSON
  repository: http://github.com/barbie/Test-CPAN-Meta-JSON

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
